### ISSUE TITLE
Remove inets application from application deps

### ISSUE THREAD

**Issue by juise** [willemdj/erlsom#27]
Hi!

I noticed that "inets" is needlessly for erlsom, and I think it will be good idea to remove it from application deps.

**Comment by schlagert** [comment]
As far as I can see `inets` is needed. When compiling XSDs `erlsom` uses the `httpc` module (HTTP client) from the inets application to download remote definitions. To be able to call functions with the `httpc` default profile `inets` must be started. [Here](http://erlang.org/doc/apps/inets/http_client.html)'s the relevant reference from the inets user's guide.

**Comment by juise** [comment]
Looks like you are absolutely right, my fault! Thanks!
