### ISSUE TITLE
Publish to hex package manager

### ISSUE THREAD

**Issue by ewildgoose** [willemdj/erlsom#32]
Hi, Hex is a package manager for Elixir and Erlang and provides straightforward dependency and installation support.

I'm not an expert, but I believe to release to hex you need only add a file "package.exs" with the following content

```
defmodule Erlsom.Mixfile do
  use Mix.Project

  @version File.read!("vsn.mk")|> String.split("=") |> List.last |> String.strip

  def project do
    [app: :erlsom,
     version: @version,
     description: "XML parser for Erlang",
     package: package]
  end

  defp package do
    [files: ~w(include src rebar.config README.md COPYING COPYING.LESSER vsn.mk),
     contributors: ["Willem de Jong"],
     licenses: ["LGPL 3.0", "GPL 3.0"],
     links: %{"GitHub" => "https://github.com/willemdj/erlsom"}]
  end
end
```

Then follow the steps:  https://hex.pm/docs/publish

Note, I believe you will need elixir installed to follow the publish steps?  I would be happy to assist with this stage (but only the owner of a package on hex can then publish new versions, hence why I'm trying to avoid forking and publishing myself)

Thanks!

**Comment by tsloughter** [comment]
You could instead update to rebar3 and publish with it: http://www.rebar3.org/v3.0/docs/publishing-packages

**Comment by willemdj** [comment]
I just published the latest version on hex, using rebar3.

Thanks for the suggestions.
