### ISSUE TITLE
Add version tag

### ISSUE THREAD

**Issue by billstclair** [willemdj/erlsom#47]
`rebar3` has the nice new `rebar.lock` feature that allows users of your library to ensure that they don't get a version that has changed incompatibly. In order to enable that, your library needs branches and/or tags to aim at in the using `rebar.config`.

You don't need to update to `rebar3` in order for using projects that DO use it to depend on your tags or branches, though `erlsom` builds for me in OTP 17.5 with `rebar3 compile` and tests successfully with `rebar3 eunit`. 

Please add at least one version tag to your repository to enable this, and continue to add new tags as your changes qualify as new releases. The only reference to a version I can see is version 1.2.1 in `vsn.mk`, but that was committed six years ago, and is only used by the `make-release` script.

**Comment by willemdj** [comment]
Done, thanks for the hint. I will try to make sure that new tags are added as appropriate.
