### ISSUE TITLE
Parsing large PCDATA

### ISSUE THREAD

**Issue by dfrese** [willemdj/erlsom#57]
Hello,

Parsing an xml file with a large PCDATA content (~100 MB, base64 encoded string) with erlsom:scan, seems to need about 10 GB of memory (100 times as much!); no matter whether I pass it a string (char list) or a binary.
Is that an 'expected behaviour', or am I using it in wrong way?

Thanks, David.

**Comment by willemdj** [comment]
Hello David,

Did you try the 'continuation_function' and/or the 'output_encoding' options?

Regards, 
Willem. 

Verstuurd vanaf mijn iPhone

**Comment by dfrese** [comment]
I now tries output_encoding "utf8" - see no effect on memory consumption.
What kind of continuation_function should I pass to reduce the needed memory? - I suspect it has somethings to do with character lists used internally while parsing?

**Comment by willemdj** [comment]
No, with the continuation function you can pass the xml in several parts to the parser, so it is not necessary to have everything in memory. See the reference documentation.

**Comment by dfrese** [comment]
Ah, sorry for not trying that first! But it does not help. Just takes a bit longer before mem goes up (maybe it's even more memory). Should that work even within a single PCDATA content of an element?

**Comment by willemdj** [comment]
Unfortunately I am not able to really investigate at this moment, sorry.

**Comment by dfrese** [comment]
Think I got it; my fault. I passed a string as the output_encoding, not an atom.
Thanks for the quick responses and help.

(Maybe an error could be thrown for invalid output_encodings instead of falling back to the list default... like with the encoding option, which must be a string, not an atom ;-))

**Comment by willemdj** [comment]
Okay, thanks for letting me know.
