### ISSUE TITLE
Data binding: case insensitive parsing

### ISSUE THREAD

**Issue by archSeer** [willemdj/erlsom#66]
We're trying to parse a few wsdl files in which they didn't camel-case the attribute names. So something like 
```erlang
erlsom:scan(WsdlFile, WsdlModel)
```
```xml
<wsdl:definitions name="MyService" targetnamespace="http://example.com/"  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  ...
</wsdl:definitions>
```
will fail to parse with the xsd model we have `'Unexpected attribute: targetnamespace'`, because the correct definition is `targetNamespace`.

Would it be possible to parse these files case insensitive?

**Comment by willemdj** [comment]
Are you using erlsom_parseXsd:xsdModel() as the "model"? You could make a copy of the module erlsom_parseXsd that uses lower case strings for the tags. So line 75 would become:

`	     atts = [#att{nm = targetnamespace, nr = 3, opt = true, tp = char},`

for example. (I didn't try it...).

Or you could even create a function to modify the result of erlsom_parseXsd:xsdModel(), I guess.

Fixing the Wsdl files might be a better option...

God luck,
Willem

**Comment by archSeer** [comment]
Hi @willemdj, thanks for bumping the version to 1.4.2! Would it be possible to build and publish a hex.pm package for v1.4.2 as well? https://hex.pm/packages/erlsom

http://www.rebar3.org/v3.0/docs/publishing-packages

**Comment by willemdj** [comment]
Done. (Sorry that it took as while.)

**Comment by archSeer** [comment]
Thank you!
