### ISSUE TITLE
scan incorrectly fails with error "Unexpected attribute: length"

### ISSUE THREAD

**Issue by ewestern** [willemdj/erlsom#79]
`test.xsd` ([Link](https://gist.github.com/ewestern/fb293e73b6698aa24abea195cfe6688a))
`test.xml` ([Link](https://gist.github.com/ewestern/fd556c597b6c87faaaefa80a2ad000c4))

```
{ok, Model} = erlsom:compile_xsd_file("test.xsd"),
erlsom:scan_file("test.xml", Model).
```
```
                    {error,[{exception,{error,"Unexpected attribute: length"}},
                            {stack,[descriptionsType,
                                    'partnerContent/seriesItems/series',
                                    'partnerContent/seriesItems',partnerContent]},
                            {received,{startElement,[],"description",[],
                                                    [{attribute,"length",[],[],"60"}]}}]}
```

**Comment by willemdj** [comment]
Hi, I just had a quick look, but are you sure your assumptions are correct? I think you have to repeat the "length" attribute on the restricted type. See [this post on stackoverflow](https://stackoverflow.com/questions/14797543/xml-schema-restriction-for-complex-types-complete-redefinition****), for example.

**Comment by ewestern** [comment]
Thanks for your quick response. 
I'm not positive my assumptions are correct, but I have some reason to think so. 
Consider the [Xml Schema Primer](https://www.w3.org/TR/xmlschema-0/#DerivByRestrict):

> Notice that types derived by restriction must repeat all the particle components (element declarations, model groups, and wildcards) of the base type definition that are to be included in the derived type. **However, attribute declarations do not need to be repeated** in the derived type definition;

Note that this is consistent with the stackoverflow post as well.

(Also, it's not dispositive, but these successfully validate with libxml and xerces ).

**Comment by willemdj** [comment]
Yes, you are right. So it is indeed something that should be fixed.

I'll try to do it, but it will probably not be soon.

Anyway, thanks for reporting this.

Op za 6 feb. 2021 om 18:23 schreef Peter France <notifications@github.com>:
