### ISSUE TITLE
Serializing large XML results in huge memory consumption

### ISSUE THREAD

**Issue by neslinesli93** [willemdj/erlsom#89]
Hi, we are dealing with huge XML files (around 100MB of base64-encoded data) and we are observing a huge spike in memory, up to 15GB of RAM. Here is an adaptation of `erlsom_example.erl` that reproduces the issue, along with a screenshot of the observer that demonstrates the memory spike.

```erl
%%% a simple example of the use of erlsom.
%%%
-module(erlsom_example).

%% user interface
-export([run/0]).

%% define records
-record('out:resultType', {anyAttribs, result}).
-record('out:errorType', {anyAttribs, errorCode, errorDescription}).

run() ->
  %% compile xsd
  {ok, ModelIn} = erlsom:compile_xsd_file(example_in_xsd(), [{prefix, "in"},
                                                             {strict, false}]),
  {ok, ModelOut} = erlsom:compile_xsd_file(example_out_xsd(),[{prefix, "out"},
                                                              {strict, false}]),

  %% parse xml
  {ok, _, _} = erlsom:scan_file(example_in_xml(), ModelIn),

  Data = crypto:strong_rand_bytes(100000000),
  Encoded = base64:encode(Data),
  Result = #'out:errorType'{errorCode = "01", errorDescription = Encoded},

  %% generate xml.
  Response = #'out:resultType'{result=Result},
  {ok, XmlResult} = erlsom:write(Response, ModelOut),
  io:format("Result size: ~p~n", [string:length(XmlResult)]),
  ok.


%% this is just to make it easier to test this little example
example_in_xsd() -> filename:join([codeDir(), "example_in.xsd"]).
example_out_xsd() -> filename:join([codeDir(), "example_out.xsd"]).
example_in_xml() -> filename:join([codeDir(), "example_in.xml"]).
codeDir() -> filename:dirname(code:which(?MODULE)).


```

![image](https://user-images.githubusercontent.com/1112539/198993320-bc34e936-bda4-45d4-8cf6-b3ae01b44775.png)

---

We tried doing some investigation, for example by removing `erlsom_lib:xmlString`, with no success. Do you know what may cause the issue? I know that there is a streaming parser, but not a streaming writer...

**Comment by willemdj** [comment]
You can pass an option to erlsom:write that tells it to return "chardata". This is a nested list of string and binary fragments. Depending on what you want to do with the result that can be quite a good solution, and it should be much more efficient.

`  {ok, XmlResult} = erlsom:write(Response, ModelOut, [{output, chardata}]),`

**Comment by neslinesli93** [comment]
Thank you for the quick reply, you nailed it, that solved the issue for us! Thank you again :)
